### ISSUE TITLE
Unable to locate supported Framework.

### ISSUE THREAD

**Issue by ptahchiev** [dobromyslov/sencha-extjs-maven#2]
I tried it with sencha cmd v5.0.2.270 and I got this exception:

[INFO] --- exec-maven-plugin:1.2.1:exec (sencha-compile) @ sencha-extjs-maven ---
Sencha Cmd v5.0.2.270
[ERR] Unable to locate supported Framework.

```
  Please ensure this command was executed from a supported framework
  directory or that a framework directory was specified via the -sdk switch.
  For example:

      sencha -sdk /path/to/framework-dir generate app AppName path/to/app
```

[ERR] com.sencha.exceptions.ExState: Not a framework directory : C:\workspace\sencha-extjs-maven/src/main/application
     at com.sencha.cli.AbstractCommand$Property.set(AbstractCommand.java:406)
     at com.sencha.cli.AbstractCommand.processConfigParam(AbstractCommand.java:527)
     at com.sencha.cli.AbstractCommand.configure(AbstractCommand.java:114)
     at com.sencha.command.Sencha.main(Sencha.java:129)
   Caused by: Not a framework directory : C:\workspace\sencha-extjs-maven/src/main/application
     at com.sencha.command.Sencha.setSdkPath(Sencha.java:366)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     at java.lang.reflect.Method.invoke(Unknown Source)
     at com.sencha.cli.AbstractCommand$Property.set(AbstractCommand.java:394)
     at com.sencha.cli.AbstractCommand.processConfigParam(AbstractCommand.java:527)
     at com.sencha.cli.AbstractCommand.configure(AbstractCommand.java:114)
     at com.sencha.command.Sencha.main(Sencha.java:129)

**Comment by mallim** [comment]
Whoever encounters this problem, please do as follows:

Goto ${basedir}\src\main\application

Run the following command

``` dos
sencha app upgrade 
```

**Comment by dobromyslov** [comment]
Updated this project to 1.1 version and fixed this issue.

**Comment by hlherrera** [comment]
Im trying to run the command in ${basedir}\src\main\application : 

> sencha app upgrade

but I had this error:

> Sencha Cmd v5.1.2.52
> [WRN] Did not locate framework package
> [ERR] Directory /opt/www/html/sencha-extjs-maven/src/main/application/ext not recognized as a framework
> [ERR] Cannot find file: /opt/Sencha/Cmd/repo/.sencha/codegen.json

**Comment by dobromyslov** [comment]
Did you clone the project from the repository instead of generate new one with 

```
sencha generate app -ext MyApp src/main/application
```

?

If you clone the repo then you have to place ExtJS into `ext` subfolter.
